### ISSUE TITLE
Login screen defaults to laptop screen when lid closed

### ISSUE THREAD

**Issue by xEtherealx** [linuxmint/mdm#79]
Mint 16 Cinnamon x86_64, Nvidia drivers on an HP elitebook. The initial login screen is on the laptop screen instead of the attached monitors. The actual screen area spans to one attached monitor but is black; the cursor is visible. The other screen gets no signal. In my case, the laptop is docked.

**Comment by e-mi** [comment]
I have the same problem as described here but with Mint 17.2 Cinnamon 64-bit, Cinnamon version 2.6.13, Linux kernel 3.16.0-38-generic, and NVIDIA driver 340.76 (installed via Driver Manager).

I am using Lenovo W510 with an external monitor.

The initial login is shown on the laptop although the lid is closed. The external monitor screen is black and the mouse pointer is visible. The laptop is not docked but connected to one external monitor.

Can some please help solving this problem?

Thanks.

**Comment by vlukes** [comment]
The same problem on DELL E6530 (NVIDIA graphics), Mint 17.2 KDE 64-bit. I fixed it by the following lines in /etc/mdm/SuperInit/Default:

dp1_connected=$(xrandr -q | grep "DP-1 connected")                                      
if [ -n "$dp1_connected" ]; then                                                        
    xrandr --output LVDS-0 --off --output DP-1 --auto                                   
fi

i.e., disable the internal display when an external one is attached.

**Comment by eesko** [comment]
Just upgraded to Mint 18 Mate and had this problem. Fixed with vlukes' solution (with slightly differing input names).

**Comment by renepavlik** [comment]
@clefebvre I'm sorry, don't wanna be rude, but where is the fix? it is almost 4 years since you closed this as fixed in git. I have 18.3 and still facing this issue. Have laptop in dock with closed lid, attached DVI-0 external monitor and mdm still appears on LVDS only. Expected is (when lid is closed and any external monitor is attached) to set primary to one of those connected monitors.

**Comment by mrdrthom** [comment]
+1
exact same behavior.  older asus laptop, on mint 18.3 via upgrade from 18.1, external monitor on vga

**Comment by mrdrthom** [comment]
OK, the deal is that there are two places where the external monitor needs to be set as the primary monitor.  one of these places is MDM, which sources the login screen running as root.  you do this with "mdmsetup" which provides a configuration GUI.  relevant items:
1) since mdm runs as root you need to do "sudo mdmsetup"
2) at startup the mdmsetup program checks how many monitors are connected and does not provide the monitor selection configuration if there is only one monitor, so when you run mdmsetup you need both the laptop cover open and the external monitor connected so that the program discovers two active monitors. 
3) given the above, the mdmsetup options screen will include a combo box for selecting primary monitor.  the primary monitor is where the login screen will appear, so for this use case select the external monitor as the primary monitor.

in addition, in linux mint display settings, you also need to select the external monitor as the primary monitor.  This setting determines which monitor contains the start menu bar.  for this use case you want to set the external monitor as the primary monitor.  this again is done with both displays active. 

as far as I know, the linux mint setting is per user and is completely distinct from the mdm configuration.

**Comment by renepavlik** [comment]
@mrdrthom good research. After playing with xrandr I was able to enable both monitors (opening the lid just showed turned-off LVDS and mint's Display properties dialog was not able to do anything with it). In that state, the mdmsetup actually showed the combobox for selecting the primary display - hurray! But after setting the DVI-0 there and restarting the mdm, all went wrong: DVI display turned off by no signal, LVDS had just the extended wallpaper without the login dialog - which apparently was on the turned-off DVI monitor. I removed the line which was added by mdmsetup:

```
PrimaryMonitor=1
```

from `/etc/mdm/mdm.conf` to fix it back to old-but-not-optimal state.
